name: Import indicators
on:
  push:
    branches:
      - master
jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Import indicators
        run: npm install && npm run import
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.token }}
          commit-message: import uploaded indicators
          title: Import uploaded indicators
          body: Import source translations from the latest uploaded indicators.
          branch: import-indicators
